name: flutter_animaciones_notificaciones
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.1
  permission_handler: ^11.3.0
  flutter_local_notifications: 19.2.1
  path_provider: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  android_intent_plus: ^4.0.2
  intl: ^0.20.2
  http: ^1.1.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/